Add ProxySQL Dashboard json
appscode/grafana-dashboards pull request #27
Opened 2022-10-28 11:28 UTC by TasdidurRahman

Signed-off-by: TasdidurRahman <tasdid@appscode.com>

2022-11-25 04:16 UTC, spectro30 requested changes

2022-11-25 04:16 UTC, spectro30 commented on proxysql/proxysql-summary.json
> +  }
add newline at the end of all files

2022-11-25 04:16 UTC, spectro30 commented on proxysql/proxysql-database.json
> +{
add namespace if not present

2022-11-25 04:16 UTC, spectro30 commented on proxysql/README.md
> +```bash
pull this PRs changes

2022-11-29 09:45 UTC, TasdidurRahman commented on proxysql/proxysql-summary.json
> +  }
added

2022-11-29 09:45 UTC, TasdidurRahman commented on proxysql/README.md
> +```bash
pulled

2022-11-29 09:45 UTC, TasdidurRahman commented on proxysql/proxysql-database.json
> +{
added

2022-11-29 09:59 UTC, spectro30 approved these changes
LGTM

2022-11-29 11:43 UTC, merged