Add Dashboards for kubeops/scanner
appscode/grafana-dashboards pull request #33
Opened 2023-01-06 09:35 UTC by ArnobKumarSaha

Signed-off-by: Arnob kumar saha <arnob@appscode.com>

2023-01-06 10:52 UTC, pkbhowmick requested changes

2023-01-06 10:52 UTC, pkbhowmick commented on scanner/app-level-cves.json
> +          "expr": "sum by(severity) (scanner_appscode_com_image_cve_count_total * on(image) group_left scanner_appscode_com_image_lineage{group=\"$group\",kind=\"$kind\",exported_namespace=\"$ns\",na
There should be a description field. After adding description, you can see an i-button in each panel right corner.

2023-01-10 04:08 UTC, pkbhowmick commented on scanner/README.md
> +Note: These dashboards are developed in **Grafana version 9.3.1**
I wonder, grafana versioned 9.x.x dashboard will perfectly work in 7.x.x or 8.x.x grafana version?

2023-01-10 04:09 UTC, pkbhowmick commented on scanner/README.md
> +Note: These dashboards are developed in **Grafana version 9.3.1**
@ArnobKumarSaha can you please check these dashboard json is also working in grafana 7.x.x and 8.x.x ?

2023-01-10 09:07 UTC, ArnobKumarSaha reviewed
Now I have re-created the Scanner Dashboards using `Grafana v7.5.11`.  Also tested that on `v8.2.3` & `v9.0.1`. Its working nicely !

2023-01-10 09:53 UTC, merged